# Server Port
server:
  port: 8082

# Logging configuration
logging:
  level:
    root: INFO

spring:
  # MongoDB
  data:
    mongodb:
      username: ricsanfre
      password: password
      host: localhost
      port: 27017
      database: recommendation
      authentication-database: admin