# Server Port
server:
  port: 8082

# Logging configuration
logging:
  level:
    root: INFO

spring:
  application:
    name: recommendation
  # MongoDB
  data:
    mongodb:
      username: ricsanfre
      password: password
      host: localhost
      port: 27017
      database: recommendation
      authentication-database: admin

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info
  # Show health details
  endpoint:
    health:
      # Show health details
      show-details: always
      # Enable liveness and readiness probes
      probes:
        enabled: true
  # Enabling exposure of env app information in applications.properties file
  info:
    env:
      enabled: true
  # Adding readiness and liveness probe states in health endpoint
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

# Configuring env info
info:
  app:
    name: recommendation
    description: "Recommendation Microservice"
    version: "1.0"
  company: ricsanfre.com

# Eureka client
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/