server:
  port: 8090

spring:
  application:
    name: "eurekaserver"

# Eureka server config
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health, info
  # Show health details
  endpoint:
    health:
      # Show health details
      show-details: always
      # Enable liveness and readiness probes
      probes:
        enabled: true
  # Enabling exposure of env app information in applications.properties file
  info:
    env:
      enabled: true
  # Adding readiness and liveness probe states in health endpoint
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

# Configuring env info
info:
  app:
    name: eurekaserver
    description: "Eureka server"
    version: "1.0"
  company: ricsanfre.com